config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :current_user do
    resources :posts, only: %i[new create edit update destroy], controller: 'posts'
  end

  resources :users, only: %i[] do
    resources :posts, only: %i[index], controller: 'users/posts'
  end
  resources :posts, only: %i[show], controller: 'posts' do
    resources :comments, only: %i[index create edit update destroy], controller: 'posts/comments'
  end
  resources :comments, only: %i[] do
    resources :reactions, only: %i[create destroy], controller: 'comments/reactions'
  end

  root to: 'home#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates_presence_of :title, :description

  after_commit :broadcast_update, on: :update
  after_commit :broadcast_destroy, on: :destroy

  private

  def trigger_post_broadcast(data)
    ActionCable.server.broadcast("post_#{id}", data)
  end

  def trigger_comments_broadcast(data)
    ActionCable.server.broadcast("post_#{id}:comments", data)
  end

  def broadcast_update
    data = {
      action: :update,
      type: :post,
      title: title,
      description: description
    }
    trigger_post_broadcast(data)
    trigger_comments_broadcast(data) if saved_change_to_title?
  end

  def broadcast_destroy
    data = {
      action: :destroy,
      type: :post
    }
    trigger_post_broadcast(data)
    trigger_comments_broadcast(data)
  end
end

app/controllers/current_user/posts_controller.rb
# frozen_string_literal: true

module CurrentUser
  class PostsController < ApplicationController
    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      @post.user = current_user

      respond_to do |format|
        if @post.save
          format.html { redirect_to post_path(@post) }
        else
          format.html { render :new }
        end
      end
    end

    def edit
      post
    end

    def update
      respond_to do |format|
        if post.update(post_params)
          format.html { redirect_to post_path(post) }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      post.destroy
      redirect_to user_posts_path(current_user)
    end

    private

    def post
      @post ||= current_user.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :title,
        :description
      )
    end
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    def index
      @comments = Posts::CommentsQuery.new(post.id, include_reactions: true).call
    end

    def create
      result = Comments::CreateService.new(params[:post_id], current_user.id, comment_params).call

      respond_to do |format|
        format.js do
          render :create, locals: {
            result: result,
            current_user: current_user
          }
        end
      end
    end

    def edit
      comment = current_user.comments.find(params[:id])

      respond_to do |format|
        format.js do
          render :edit, locals: {
            comment: comment
          }
        end
      end
    end

    def update
      result = Comments::UpdateService.new(params[:id], current_user.id, comment_params).call

      respond_to do |format|
        format.js do
          render :update, locals: {
            result: result,
            current_user: current_user
          }
        end
      end
    end

    def destroy
      result = Comments::DeleteService.new(params[:id], current_user.id).call

      respond_to do |format|
        format.js do
          render :destroy, locals: {
            result: result,
            post: post,
            comment_id: params[:id]
          }
        end
      end
    end

    private

    def post
      @post ||= Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(
        :description
      )
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/users/posts_controller.rb
# frozen_string_literal: true

module Users
  class PostsController < ApplicationController
    def index
      @posts = user.posts
    end

    private

    def user
      @user ||= User.find(params[:user_id])
    end
  end
end

app/views/posts/show.html.erb
<div id="post-id" data-post-id="<%= @post.try(:id) %>"></div>
<div id="user-id" data-user-id="<%= current_user.try(:id) %>"></div>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Home', root_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @post.user.email, user_posts_path(@post.user) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Posts", user_posts_path(@post.user) %>
    </li>
    <li class="breadcrumb-item active" aria-current="page" id="post-title-breadcrumb">
      <%= @post.title %>
    </li>
  </ol>
</nav>
<div class="row mt-4">
		<div class="col-12">
				<div class="card text-center">
					<div class="card-header" id="post-header">
						<ul class="nav nav-pills card-header-pills">
							<li class="nav-item">
								<%= link_to 'Comments', post_comments_path(@post), class: "nav-link" %>
							</li>
							<% if @post.user.id == current_user.id %>  
								<li class="nav-item">
									<%= link_to 'Edit', edit_current_user_post_path(@post), :class => 'nav-link' %>
								</li>
								<li class="nav-item">
									<%= link_to 'Delete', current_user_post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class => 'nav-link'  %>
								</li>
							<% end %>
						</ul>
					</div>
					<div class="card-body">
						<h5 class="card-title" id="post-title">
							<%= @post.title %>
						</h5>
						<p class="card-text" id="post-description">
							<%= @post.description %>
						</p>
					</div>
				</div>
		</div>
</div>