config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :current_user do
    resources :posts, only: %i[new create edit update destroy], controller: 'posts'
  end

  resources :users, only: %i[] do
    resources :posts, only: %i[index], controller: 'users/posts'
  end
  resources :posts, only: %i[show], controller: 'posts' do
    resources :comments, only: %i[index create edit update destroy], controller: 'posts/comments'
  end
  resources :comments, only: %i[] do
    resources :reactions, only: %i[create destroy], controller: 'comments/reactions'
  end

  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="container-fluid">
        <div class="row mt-4">
          <div class="col-2">
            <nav class="nav flex-column">
              <div class="card">
                <div class="card-body">
                  Welcome <strong><%= current_user.email %></strong>
                </div>
              </div>
              <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">
                    <%= link_to 'Home', root_path %>
                  </li>
                  <li class="list-group-item">
                    <%= link_to 'New Post', new_current_user_post_path %>
                  </li>
                  <li class="list-group-item">
                    <%= link_to 'My Posts', user_posts_path(current_user) %>
                  </li>
                  <li class="list-group-item">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
          <div class="col-8">
            <%= yield %>
          </div>
          <div class="col-2">
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>